

default: &default
  adapter: sqlite3
  
  
  
  
  


development:
  <<: *default
  database: db/solidus_development.sqlite3
test:
  <<: *default
  database: db/solidus_test.sqlite3
production:
  <<: *default
  database: db/solidus_production.sqlite3


